// Abstract all mutation names
export const CREATE_POST = 'CREATE_POST'
export const READ_POST = 'READ_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const UPDATE_ADMIN_STATUS = 'UPDATE_ADMIN_STATUS'
export const UPDATE_CLICKED_ID = 'UPDATE_CLICKED_ID'
export const UPDATE_LOCAL_STORAGE = 'UPDATE_LOCAL_STORAGE'
export const DELETE_POST = 'DELETE_POST'
export const FIND_SINGLE_ELEMENT = 'FIND_SINGLE_ELEMENT'